name: trademark_guessing_game
description: A trademark guessing game built with Flutter

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^5.1.0       # For sound effects
  shared_preferences: ^2.2.2 # For storing high scores
  cached_network_image: ^3.4.1 # For loading images from URLs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/correct.mp3
    - assets/wrong.mp3
